### ISSUE TITLE
'Model' object has no attribute '_ctx'

### ISSUE THREAD

**Issue by nomocp** [nomic-ai/pygpt4all#16]
I tried running the tutorial code at readme.md, I have installed the pyllamacpp module. 

```
from pyllamacpp.model import Model

def new_text_callback(text: str):
    print(text, end="")


if __name__ == "__main__":
  prompt = "Once upon a time, "
  model = Model(ggml_model='chat/gpt4all-model.bin', n_ctx=512)
  model.generate(prompt, n_predict=55, new_text_callback=new_text_callback, n_threads=8)
```

The traceback
`Traceback (most recent call last):
  File "...\gpt4\llama.py", line 9, in <module>
    model = Model(ggml_model='chat/gpt4all-model.bin', _ctx=512)
  File "C:\Users\...\Python310\lib\site-packages\pyllamacpp\model.py", line 53, in __init__
    raise Exception(f"File {ggml_model} not found!")
Exception: File chat/gpt4all-model.bin not found!
Exception ignored in: <function Model.__del__ at 0x00000257AED04280>
Traceback (most recent call last):
  File "C:\Users\...\Python310\lib\site-packages\pyllamacpp\model.py", line 136, in __del__
    pp.llama_free(self._ctx)
AttributeError: 'Model' object has no attribute '_ctx' `

**Comment by nocpinmylf** [comment]
My bad, i passed a wrong ggml path
