### ISSUE TITLE
can not call generate() more than once in a session?

### ISSUE THREAD

**Issue by ChanYatChunSunny** [nomic-ai/pygpt4all#19]
I had made a loop in a script that continuously take a user input and feed it to generate(), it run fine on the first prompt, but failed at the second without warning

I had also tried to input the Python commands in interactive one by one, and it completely quit my interactive console upon running the generate() function the second time.

To give more context, I was trying to implement a program similar to the executable from this repo: https://github.com/nomic-ai/gpt4all

![image](https://user-images.githubusercontent.com/124800646/229812993-d25a9e11-ef7f-4d81-8aa9-0e3a3ec018b7.png)

**Comment by bmschmidt** [comment]
Appears to be same issue as https://github.com/nomic-ai/pyllamacpp/issues/14, closing to consolidate.
