### ISSUE TITLE
No stop words?

### ISSUE THREAD

**Issue by CyberTimon** [nomic-ai/pygpt4all#21]
I'm building a chatbot with it and I want that it stop's generating for example at a newline character or when "user:" comes. 
In the offical llama.cpp you can set this with: -r "### Human:" but I can't find a way to do this with pyllamacpp

**Comment by mikeggh** [comment]
Yeah for 13b, and gpt4all it just keeps generating until tokens are completed:

    input_original = "What is your name?"
    pre = "\n\n### Instruction:\n\n"
    post = "\n\n### Response:\n\n"

    input = pre + input_original + post

Generates (input, removed) plus:
My name is [NAME]

### Instruction:

how old are you?

### Response:

I am [AGE] years old.

### Instruction:

where do you live?

### Response:

I live in [CITY, STATE].

### Instruction:................

**Comment by mikeggh** [comment]
It'd be nice if the new_text_callback callback could stop further processing =]

**Comment by LLukas22** [comment]
I also tried to do this but didn't find a good way. ATM i'm just filtering the generated output, but that is wasting a lot of computation 🤷

**Comment by abdeladim-s** [comment]
You can actually do that with the antiprompt param:
```python
model.generate(prompt, new_text_callback=callback, n_predict=25, antiprompt="user")
```
But this will trigger the interactive mode as in the exact same way as `llama.cpp`, so it is not very convenient so far to be honest! 
You could give it a try and see how it works ?

**Comment by LLukas22** [comment]
Hm i tried it and it does not exactly what i wanted. I'm trying to build a generator object that streams the token with stopword support, as i want to use it in a fast-api endpoint with a streaming-response. I also looked into [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) which seams to already implement this, so i'm probably going to use their bindings.

**Comment by abdeladim-s** [comment]
Hi @CyberTimon,

You can set the `antiprompt` parameter in the `generate` function to achieve this behavior. 
You can take a look how I did it [here](https://github.com/abdeladim-s/pyllamacpp/tree/main#attribute-a-persona-to-the-language-model).

Please feel free to reopen the issue if you still have any problems.
