### ISSUE TITLE
Error in the code if using the pypi version of pyllamacpp

### ISSUE THREAD

**Issue by ParisNeo** [nomic-ai/pygpt4all#23]
Hi, I was testing the code you provided after installing the module from the pypi repository.

When I launch it, I get this:
```
Une exception s'est produite : AttributeError
'_pyllamacpp.llama_context_params' object has no attribute 'n_threads'
```

It works when I remove the n_threads parameter. I guess it is a new parameter that was not included in the package submitted to Pypi.

Can you please update the code.

And one more question. It takes too much time to make the model generate the output. It seems slower than the exe version.

**Comment by abdeladim-s** [comment]
Hi,

* The pakcage submitted to Pypi is up to date, Please see my comment #8 and read the docs. 

* If it seems slower, as I mentioned  in the readme, you might need to try to build it from source. Please give it a try and let us know ?
