### ISSUE TITLE
Exception: Invalid file magic. Must be an old style ggml file.

### ISSUE THREAD

**Issue by hugomztl** [nomic-ai/pygpt4all#30]
>pyllamacpp-convert-gpt4all gpt4all-lora-quantized.bin tokenizer.model /pyllamacpp

unable to convert, I get this error :

```
Namespace(gpt4all_model='gpt4all-lora-quantized.bin', tokenizer_model='tokenizer.model', fout_path='/pyllamacpp')
converting gpt4all-lora-quantized.bin
Traceback (most recent call last):
  File "/home/hugomztl/.local/bin/pyllamacpp-convert-gpt4all", line 8, in <module>
    sys.exit(main())
  File "/home/hugomztl/.local/lib/python3.10/site-packages/pyllamacpp/scripts/convert_gpt4all.py", line 19, in main
    convert_one_file(args.gpt4all_model, tokenizer)
  File "/home/hugomztl/.local/lib/python3.10/site-packages/pyllamacpp/scripts/convert.py", line 92, in convert_one_file
    write_header(f_out, read_header(f_in))
  File "/home/hugomztl/.local/lib/python3.10/site-packages/pyllamacpp/scripts/convert.py", line 34, in write_header
    raise Exception('Invalid file magic. Must be an old style ggml file.')
Exception: Invalid file magic. Must be an old style ggml file.
```

**Comment by abdeladim-s** [comment]
@hugomztl, I think the model you are trying to convert is either already converted or corrupted. 
Have you tried to run it as is first ? is it working with the original `llama.cpp` binary ?

**Comment by MartinKei** [comment]
@abdeladim-s 
I have a similar issue. 

```
llama_model_load: loading model from '/home/zombie/gpt4all-lora-quantized-ggml.bin' - please wait ...
/home/zombie/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
        you most likely need to regenerate your ggml files
        the benefit is you'll get 10-100x faster load times
        see https://github.com/ggerganov/llama.cpp/issues/91
        use convert-pth-to-ggml.py to regenerate from original pth
        use migrate-ggml-2023-03-30-pr613.py if you deleted originals
```

But said scripts do not exist anymore in the current `master` branch
https://github.com/ggerganov/llama.cpp#using-gpt4all

What's the proper source for the model?

**Comment by MartinKei** [comment]
@abdeladim-s 
I have downloaded and build llama.cpp - with this one it works.

**Comment by abdeladim-s** [comment]
> @abdeladim-s I have a similar issue.
> 
> ```
> llama_model_load: loading model from '/home/zombie/gpt4all-lora-quantized-ggml.bin' - please wait ...
> /home/zombie/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
>         you most likely need to regenerate your ggml files
>         the benefit is you'll get 10-100x faster load times
>         see https://github.com/ggerganov/llama.cpp/issues/91
>         use convert-pth-to-ggml.py to regenerate from original pth
>         use migrate-ggml-2023-03-30-pr613.py if you deleted originals
> ```
> 
> But said scripts do not exist anymore in the current `master` branch https://github.com/ggerganov/llama.cpp#using-gpt4all
> 
> What's the proper source for the model?

@MartinKei, You can download a ready to use model, please take a look at this [section](https://github.com/nomic-ai/pyllamacpp#gpt4all).
