### ISSUE TITLE
Problems installing pyllamacpp with docker 

### ISSUE THREAD

**Issue by abnersunigaart** [nomic-ai/pygpt4all#39]
Hello guys I'm trying to create a docker image with your lib, but I'm getting this error:

#5 56.15       CMake Error at llama.cpp/CMakeLists.txt:230 (add_library):
#5 56.15         Cannot find source file:
#5 56.15       
#5 56.15           ggml.c
#5 56.15       
#5 56.15         Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
#5 56.15         .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
#5 56.15       
#5 56.15       
#5 56.15       CMake Error at llama.cpp/CMakeLists.txt:241 (add_library):
#5 56.15         Cannot find source file:
#5 56.15       
#5 56.15           llama.cpp
#5 56.15       
#5 56.15         Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
#5 56.15         .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
#5 56.15       
#5 56.15       
#5 56.15       CMake Error at llama.cpp/CMakeLists.txt:230 (add_library):
#5 56.15         No SOURCES given to target: ggml
#5 56.15       
#5 56.15       
#5 56.15       CMake Error at llama.cpp/CMakeLists.txt:241 (add_library):
#5 56.15         No SOURCES given to target: llama
#5 56.15       
#5 56.15       
#5 56.15       CMake Generate step failed.  Build files cannot be regenerated correctly.

Dockerfile:
```
FROM python:3.10.11-bullseye

COPY requirements.txt .

RUN pip install -r requirements.txt
```

requirements.txt:
```
pyllama==0.0.9
pyllamacpp==1.0.6
transformers==4.27.4
llama-cpp-python==0.1.23
langchain==0.0.132
```

What could it be?

**Comment by Krishnacore** [comment]
Try install it like this
```
git clone --recursive https://github.com/nomic-ai/pyllamacpp && cd pyllamacpp
pip install .
```

**Comment by abdeladim-s** [comment]
@abnersunigaart, maybe you forget to clone the submodule, please try the what @Krishnacore suggested.
