### ISSUE TITLE
ggml to the new format

### ISSUE THREAD

**Issue by amrrs** [nomic-ai/pygpt4all#40]
It seems that llama.cpp has started using a new model version.

And this library being the wrapper isn't working for me. 

Could you please check into this - 

https://github.com/ggerganov/llama.cpp#using-gpt4all

Might require some changes in the readme

**Comment by mallorbc** [comment]
I am having a similar issue I believe.  Though I am trying to work with GPTJ models so that could be the cause as well.

**Comment by LLukas22** [comment]
For me doing it as described in the llama.cpp documentation worked.
Calling the conversion scripts in this order resulted in a working model:
```
python3 convert-gpt4all-to-ggml.py models/gpt4all-7B/gpt4all-lora-quantized.bin ./models/tokenizer.model 
python3 migrate-ggml-2023-03-30-pr613.py models/gpt4all-7B/gpt4all-lora-quantized.bin models/gpt4all-7B/gpt4all-lora-quantized-new.bin
```

**Comment by amrrs** [comment]
@LLukas22 what was the output of the first line of code? that code doesn't seem to be storing the model anywhere

**Comment by LLukas22** [comment]
@amrrs  As far as i know it overwrites the model you passed in and saves a copy with *.orig in the same directory. I dont have my converted gpt4all model here atm but i have uploaded a converted alpaca model here: https://huggingface.co/LLukas22/alpaca-native-7B-4bit-ggjt

If you want i could also upload my converted gpt4all model tomorrow.

**Comment by amrrs** [comment]
@LLukas22 Thanks for sharing. If you could do that, it'd be a great help

**Comment by LLukas22** [comment]
@amrrs Alright thanks to the almighty recycle bin i still had it laying around here you go: https://huggingface.co/LLukas22/gpt4all-lora-quantized-ggjt

**Comment by abdeladim-s** [comment]
Have you guys tried the script I've provided in the `readme`? 
because the script is merging the two steps into one, but it is the same as described in the `llama.cpp` repo

**Comment by LLukas22** [comment]
Had a look at it and i guess it should work. I basicaly did the same thing for the Alpaca model but changed the scripts to only write out the final converted file as i had some trouble with the path management of the scripts. I guess the conversion of old ggml model to the newer format is still something the LLaMa.ccp has to simplify as needing 2 different scripts is kind of overcomplicated, especially if you need different scripts for different models.

**Comment by manuzrpEd** [comment]
@abdeladim-s In the `readme` file you call `pyllamacpp-convert-gpt4all` but I don't find it anywhere in your repo.
Following @LLukas22 2 commands from llama.cpp repo worked for me.
Or did you mean to run the script `setup.py`? Please clarify.

**Comment by manuzrpEd** [comment]
@abdeladim-s I get it now, you meant to run `pyllamacpp/scripts/convert_gpt4all.py`. It works, but it was not clear from the `readme` file. Thank you.

**Comment by abdeladim-s** [comment]
@manuzrpEd, the script is exposed as an entry script, so once you activated the `venv` it will be available from the command line. 
Have you followed the `readme` instructions exactly and found any issues ?
