### ISSUE TITLE
model.py throwing an exception : 'NoneType' object is not callable

### ISSUE THREAD

**Issue by AlbelTec** [nomic-ai/pygpt4all#47]
here is the exception after having result.

```
Exception ignored in: <function Model.__del__ at 0x0000018BFFE09310>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openai\lib\site-packages\pyllamacpp\model.py", line 138, in __del__
TypeError: 'NoneType' object is not callable
```
here is the code based on langchain :

```
llm = GPT4All(model="models/gpt4all-converted.bin",n_ctx=1024)
llm_chain = LLMChain(prompt=prompt, llm=llm)
input = {"question":question,"references":references_text}
result = llm_chain.run(input)
```
any insight ?

**Comment by abdeladim-s** [comment]
Hi @AlbelTec,

I think you are using an old version of the package?
Could you please check ?

**Comment by AlbelTec** [comment]
Hi @abdeladim-s I checked and my version is : v1.0.6 this is the latest

**Comment by abdeladim-s** [comment]
@AlbelTec, that's weird, because I have fixed that error in a recent version.  
Could you please try a regular `venv` instead of `Anaconda` ?
