### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by hinthornw** [nomic-ai/pygpt4all#51]
Could we please cut a new release to get [these changes](https://github.com/nomic-ai/pyllamacpp/commit/815c32fe2db43b63d4cafcdec90e1287f5d2ceb3) landed in pypi?

**Comment by abdeladim-s** [comment]
hi @hinthornw, 
Sorry for this, but I am still making some changes to the API, so didn't want to push a new release until I get a stable version. 
You can always consider building from source.

**Comment by abdeladim-s** [comment]
@hinthornw, New release [v1.0.7](https://github.com/nomic-ai/pygpt4all/tree/v1.0.7) pushed to pypi
