### ISSUE TITLE
can't mlock because it's not supported on this system

### ISSUE THREAD

**Issue by Naugustogi** [nomic-ai/pygpt4all#54]
Using Windows, on the other side llama.cpp works as fine with keeping the model in ram.
Loading the model each time for use is annoying.

**Comment by abdeladim-s** [comment]
@Naugustogi, `mlock` should be supported, Do you get any errors! 

Btw, loading the model does not take much time! it is almost instant now! Why it that annoying ?

**Comment by abdeladim-s** [comment]
@Naugustogi I think that error is coming from the `ggml` library. 
Everything is working normally on my side. 
Could you please try to build it from source ?

**Comment by Naugustogi** [comment]
> @Naugustogi I think that error is coming from the `ggml` library. Everything is working normally on my side. Could you please try to build it from source ?

I am unable to rebuild and have to rely on other peoples upload. You can close this issue if you want. For now i have to wait for speed modifications, Model loading and staying in ram is fine, it just takes abit time in my case. The initial problem wasn't mlock. I simply mistook the loading time for the model generation time.
