### ISSUE TITLE
Problem with some processors

### ISSUE THREAD

**Issue by ParisNeo** [nomic-ai/pygpt4all#73]
Hi, Some people using the gpt4all-ui that relies on your python bindings reported problems with the code hanging at the line that imports the pyllamacpp module.

![image](https://user-images.githubusercontent.com/827993/233804643-81b650d0-2451-486c-8e80-a3532e089fda.png)

This happens the same on windows or on linux. It seems that there is something missing in their hardware.

**Comment by abdeladim-s** [comment]
Duplicate of #53
