### ISSUE TITLE
WARNING - UnicodeDecodeError of bytes b'\xad'

### ISSUE THREAD

**Issue by pycloux** [nomic-ai/pygpt4all#87]
Hello,

When running with model ```ggml-gpt4all-j-v1.3-groovy.bin```, I have a lot of ```{model.py:85} WARNING - UnicodeDecodeError of bytes b'\xad'``` in the INFO log.

This is related to an Unicode error in pygptj/model.py (line 85 as specified).

Not blocking as this is a warning.

**Comment by abdeladim-s** [comment]
Hello @pycloux,

It is the same issue as #76 
Please update the package and give it a try now ?

I believe the issue should be solved.
(ensure you have pygptj version 1.0.10).

**Comment by pycloux** [comment]
Hi @abdeladim-s,

Just tested.
It fixed the issue for me.
Thanks 👍
