### ISSUE TITLE
How do you generate the doc?

### ISSUE THREAD

**Issue by mkinney** [nomic-ai/pygpt4all#89]
I see there is a `mkdocs.yml` file, but not sure how to create the docs. What requirements are necessary?

I tried `pip install mkdocs`, and ran `mkdocs build` but I got an error:

```
% mkdocs build
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')
  in "/nix/code/pygpt4all/mkdocs.yml", line 45, column 20
```

I've tried installing a few other packages, but to no avail.

Would it make sense to generate then add the generated docs somewhere? (perhaps in this repo even?)

**Comment by mkinney** [comment]
Note that the most recent build has an error in the build related to doc gen. See https://github.com/nomic-ai/pygpt4all/actions/runs/4826093284/jobs/8598692802

**Comment by mkinney** [comment]
Oh. I see the pages are here: https://nomic-ai.github.io/pygpt4all/ (thanks for updating the project info on the right)

**Comment by abdeladim-s** [comment]
@mkinney, You can generate the docs locally using `mkdocs serve` ( You can check the requirements from the Github workflow `docs`)
They are actually hosted in the repo, check the branch `gh-pages`. 
Yeah, I've updated the project info recently.

**Comment by mkinney** [comment]
Hmm...

```
(venv) sweet pygpt4all % mkdocs serve
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')
  in "/nix/code/pygpt4all/mkdocs.yml", line 45, column 20
```

What package(s) might need to be installed for that?

**Comment by abdeladim-s** [comment]
I think you need to install the extensions.
try:
```shell
pip install mkdocs-material-extensions
pip install mkdocs-macros-plugin
```

**Comment by mkinney** [comment]
I had those installed (after seeing the .github workflow for building the docs), but I still get the same error. 

Not a big deal. I'm trying to run this from a mac. If the docs are auto generated and available on the gh page, then I'm ok if we just close this issue.

**Comment by abdeladim-s** [comment]
It is working smoothly on my Linux machine, not sure about mac. 

OK, feel free to reopen it if you have any other issue.
