### ISSUE TITLE
Problem with GPT4All.___init___ 

### ISSUE THREAD

**Issue by horvatm** [nomic-ai/pygpt4all#96]
Hi.

Thank you for making py interface to GPT4All. I have tried 

```
from pygpt4all import GPT4All
model = GPT4All('ggml-gpt4all-l13b-snoozy.bin')
```
with ggml-gpt4all-l13b-snoozy.bin having proper md5sum

```
md5sum ggml-gpt4all-l13b-snoozy.bin
91f886b68fbce697e9a3cd501951e455  ggml-gpt4all-l13b-snoozy.bin
```
but I get an error. Can you give a hint, what I am doing wrong?

The GPT4All_J works without a problem.

Best, Martin 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 1
----> 1 model = GPT4All('ggml-gpt4all-l13b-snoozy.bin')

File ~<my dir>/gpt4all-env/lib/python3.10/site-packages/pygpt4all/models/gpt4all.py:64, in GPT4All.__init__(self, model_path, prompt_context, prompt_prefix, prompt_suffix, log_level, n_ctx, seed, n_parts, f16_kv, logits_all, vocab_only, use_mlock, embedding)
     62 # set logging level
     63 set_log_level(log_level)
---> 64 super(GPT4All, self).__init__(model_path=model_path,
     65                               prompt_context=prompt_context,
     66                               prompt_prefix=prompt_prefix,
     67                               prompt_suffix=prompt_suffix,
     68                               log_level=log_level,
     69                               n_ctx=n_ctx,
     70                               seed=seed,
     71                               n_parts=n_parts,
     72                               f16_kv=f16_kv,
     73                               logits_all=logits_all,
     74                               vocab_only=vocab_only,
     75                               use_mlock=use_mlock,
     76                               embedding=embedding)

TypeError: Model.__init__() missing 1 required positional argument: 'ggml_model'

**Comment by abdeladim-s** [comment]
Hi @horvatm,

Thank you for using the interface.

if `GPT4ALL_J` is working then I think you are still using an old version of `pyllamacpp`. 
please try ?
```shell
pip install -U pyllamacpp
```

**Comment by horvatm** [comment]
Yes, this did the trick. Thank you !!!
