### ISSUE TITLE
Missing dependency numpy

### ISSUE THREAD

**Issue by leoncente** [nomic-ai/pygpt4all#97]
When attempting to use the library, I receive an error message indicating that the numpy module is missing. However, numpy is not listed as a dependency and doesn't install automatically.
![Screenshot (76)](https://user-images.githubusercontent.com/47432876/235807684-cb4dd817-5f46-4c6b-8207-a647f43da6af.png)

**Comment by abdeladim-s** [comment]
thanks @leoncente for letting me know.

I will add it to the dependencies on the next release. 

you can just install it manually for now 
```shell
pip install numpy
```

**Comment by kentative** [comment]
also need to import in model.py

```import numpy as np```

**Comment by abdeladim-s** [comment]
@kentative, you do not need to import anything!
It should be fixed by now anyway, just try to update the package!

**Comment by Free-Radical** [comment]
FYI just tried, not fixed so far.

**Comment by abdeladim-s** [comment]
Thanks @Free-Radical for letting me know.
Please update `pygptj to 2.0.3` and give it another try ?
